defaults:
  - _self_
  - env
  - uav

# 训练设备
device: "cuda:0"

# launch文件地址
launchFile: multi_uav_static_env.launch

# 训练参数
retrain: True  # 是否重新训练
epochs: 1e5  # 训练轮数
seed: 0  # 随机种子
actorLearningRate: 3e-4  # 策略网络学习率
criticLearningRate: 3e-3  # 动作价值网络学习率
alpha: 0.01  # alpha值
alphaLearningRate: 3e-4  # alpha的学习率
targetEntity: 0.01  # 目标熵
gamma: 0.99  # 奖励折扣因子
tau: 0.005  # soft update参数
numEpisodes: 500  # 训练轮次
bufferSize: 10000  # 经验回放池容量
minimalSize: 100  # 最小容量
batchSize: 64  # 批次大小
actorLearningRateDecayStep: 500  # actor学习率衰减步长
actorLearningRateDecayGamma: 0.1  # actor学习率衰减系数
criticLearningRateDecayStep: 500  # critic学习率衰减步长
criticLearningRateDecayGamma: 0.1  # critic学习率衰减系数


# wandb参数
wandb:
  project: XTDrone_DRL
  name: navigation_training
  entity: XTDrone-DRL-UAV-Navigation
  mode: offline # online
  run_id: kw9xf9k9